name: Seedbank
options:
  bundleIdPrefix: com.shimondeitel.seedbankapp
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Seedbank:
    type: application
    platform: iOS
    sources:
      - path: Seedbank
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.seedbankapp
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Seedbank/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  SeedbankTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SeedbankTests
      - path: Seedbank.storekit
    dependencies:
      - target: Seedbank
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.seedbankapp.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  SeedbankUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: SeedbankUITests
    dependencies:
      - target: Seedbank
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.seedbankapp.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Seedbank:
    build:
      targets:
        Seedbank: all
        SeedbankTests: [test]
        SeedbankUITests: [test]
    test:
      targets:
        - SeedbankTests
        - SeedbankUITests
